version: '3.8'
services:
  api_service:
    build: .
    restart: always
    ports:
      - '8080:8080'
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
volumes:
  db:
    driver:
      local