apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-spring-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kotlin-spring-demo
  template:
    metadata:
      labels:
        app: kotlin-spring-demo
    spec:
      containers:
        - name: kotlin-spring-demo-deployment
          image:  ghcr.io/tmartipe/kotlin-spring-demo:latest
          ports:
            - containerPort: 8080